--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Xd-pro/Pockit
build-by-default: true
branches:
- main
projects:
  Pockit:
    path: ""
    libs:
      - src: Muqsit/InvMenu/InvMenu
        version: 4.3.5
        branch: "4.0"
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ~2.0.0
...
