--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Xd-pro/Pockit
build-by-default: true
branches:
- main
libs: 
- {
  src: Muqsit/InvMenu/InvMenu
}
projects:
  Pockit:
    path: ""
...
