---
name: PocKit
version: 0.0.1
main: LemoniqPvP\PocKit\Main
api: 4.0.0
src-namespace-prefix: LemoniqPvP\PocKit

commands:
  kiteditor:
    permission: pockit.command.kiteditor
    description: Edit kits visually
  
permissions:
  pockit.command.kiteditor:
    description: Edit kits visually
    default: op

...
